### ISSUE TITLE
ldc2: simple Program exited with code -11

### ISSUE THREAD

**Issue by mw66** [Cyroxin/Elembuf#3]
$ cat cb.d
```
#!/usr/bin/env dub
/+ dub.sdl:
name "app"
dependency "elembuf" version="~>1.1.1"
+/

import buffer;

void main() {
        Buffer!() bufchar = Buffer!()();
        assert(bufchar == "");
}
```
with ldc2/bin/dub

```
$ dub cb.d
Program exited with code -11
```

**Comment by Cyroxin** [comment]
Heya!

Could you try the changed buffer source file at master? CI is not reporting any issues so I'll be testing it locally as well. What architecture are you running on (X86/AArch64/...)? What is your current kernel version? The master fix should work if your kernel is below 3.17 or if there is syscall number mistake.

**Comment by Cyroxin** [comment]
<details>

~$ cat issue.d

 ```
#!/usr/bin/env dub
/+ dub.sdl:
name "app"
dependency "elembuf" version="~>1.1.2"
+/

import buffer;
import std.stdio;

void main() {
        Buffer!() bufchar = Buffer!()();
        assert(bufchar == "");
        "finished".writeln;
}
 ```
~$ dub issue.d
 ```
finished 
 ```
----
</details>

I've now tested on Ubuntu and fixed a few potential compatibility issues. You can add a dependency on the newest version [v1.1.2](https://github.com/Cyroxin/Elembuf/releases/tag/v1.1.2). The project depended on having the latest compiler version, which is now fixed with the new release. Please inform me if your issue is fixed with the new version. Some architecture specific constructor optimizations were removed in the new release, so if all possible, please do inform me your arch so that I may re-add them.

**Comment by mw66** [comment]
my env:
```
$ uname -a
Linux  4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue.net
Ubuntu 18.04.2 LTS
```

The original err with dmd of verion 1.1.1 was:
```
$ dub cb.d
core.exception.AssertError@///.dub/packages/elembuf-1.1.1/elembuf/source/buffer.d(258): Assertion failure
----------------
??:? _d_assertp [0x7f6134840f79]
///.dub/packages/elembuf-1.1.1/elembuf/source/buffer.d:258 nothrow @nogc @trusted char[] buffer.Buffer!(char, false).Buffer.gen() [0x7f613483ff8d]
///.dub/packages/elembuf-1.1.1/elembuf/source/buffer.d:361 nothrow @nogc buffer.Buffer!(char, false).Buffer buffer.Buffer!(char, false).Buffer.opCall() [0x7f61348400d0]
cb.d:10 _Dmain [0x7f613483fedc]
Program exited with code -11
```

With version 1.1.2, both dmd and ldc2 works now, no longer error  code -11.

Thanks for the fix.
